#define AUDIOTAP_MAJOR 2
#define AUDIOTAP_MINOR 0
#define AUDIOTAP_REV 0

#define STR(x) #x
#define MACROSTR(x) STR(x)
#if AUDIOTAP_REV > 0
#define AUDIOTAP_VERSION MACROSTR(AUDIOTAP_MAJOR) "." MACROSTR(AUDIOTAP_MINOR) "." MACROSTR(AUDIOTAP_REV)
#else
#define AUDIOTAP_VERSION MACROSTR(AUDIOTAP_MAJOR) "." MACROSTR(AUDIOTAP_MINOR)
#endif
